# Site
repository: geminiperseus.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hur Muhammad
title: Solutions Architect
email: hur.info@gmail.com
website: www.github.com/geminiperseus

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: https://www.linkedin.com/in/geminiperseus
github_username:  geminiperseus
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: https://www.linkedin.com/in/geminiperseus
linkedin_username: https://www.linkedin.com/in/geminiperseus
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  An AWS certified technology professional with 19 years of technical experience in product development and management. Recognized success in creating products from ideation to POC to production. Rich experience of technology leadership in conceptualizing products, formulating technical roadmaps, building/managing high performance teams, delivering award winning products and creating business value.<br /> <br />
  I am most skilled in: <mark>Java</mark>, <mark>Spark</mark>, <mark>Spring</mark>, <mark>AWS</mark> and <mark>Angular</mark>

content:      
  - title: Value Proposition # Title for the section
    layout: text # Type of content section (list/text)
    content: | 
      - Transforming business needs to value driven solutions in collaboration with all stakeholders
      - Leading large, complex global products delivery with major focus on Big Data, AI/ML and Cloud technologies
      - Consistently leading complex, challenging, high visible, fast-paced and demanding firm wide initiatives
      - Driving Artificial Intelligence/Machine Learning (AI/ML) strategy and Public Cloud blueprints for products transformation within a technology organization
      - Creating business value through successful AI/ML and Cloud POCs leading to solutions in production
      - Promoting inclusiveness and partnership by engaging all required teams to build solutions
      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TIAA Cref
        link: www.tiaa.org
        #  link_text: tiaa.org
        sub_title: Senior Solutions Architect
        caption: September 2016 - Present
        description: | # this will include new lines to allow paragraphs
          <mark>GOFOLIO</mark> Gofolio is the tool used by investment managers to create portfolios for clients. There are multiple options available to pick from such as equity, stocks etc.<br /> <br />
          <mark>SFV Designer</mark> SFV Designer is used by operations to create new services and features that are available in multiple other areas for investment managers to choose from.<br /> <br />
          <mark>Fee Calculation Engine</mark> Fee Calculation Engine is used to calculate fees for clients on their 401k services.<br /> <br />
          <mark>Responsibilities</mark><br />
          - Enhanced and build new functions for GOFOLIO application.<br />
          - Used free-maker template and jQuery to build the UI.<br />
          - Build SFV designer from scratch using Angular 2 and Spring Boot.<br />
          - Used rolling data sources in the application to store data in multiple databases.<br />
          - Created automation scripts for testing.<br />
          - Used Hadoop to calculate fees for clients.<br />
          - Migrated Fee Calculation Engine from spark 1.6 to spark 2.<br />
          - Migrated Fee Calculation Engine to AWS cloud to utilize better resources.<br />
          - Used Apache Camel AWS along with S3 and SNS services.<br />
          - Build business rules using Rule Book.<br />
          - Wrote REST services to fetch data from Oracle database.<br />
          - Used Log4j for logging and debugging.<br />
          - Used J unit for writing test cases for the classes.<br /> <br />
          <mark>Environment:</mark> JIRA, Angular2, Free maker, PL/SQL Developer, AWS, Eclipse 3.4, Gitlab, Spring 3.0, jQuery, Jenkins, JUnit, Log4J, ATDD, Apache Camel, Cucumber, Selenium, Sonar, Java8
      - layout: left
        title: Capital One
        link: www.capitalone.org
        #  link_text: tiaa.org
        sub_title: Solutions Architect
        caption: September 2011 - September 2016
        description: | # this will include new lines to allow paragraphs
            I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      - layout: left
        title: State of Maryland
        link: www.courts.state.md.us
        #  link_text: tiaa.org
        sub_title: Senior Java Engineer
        caption: October 2010 - September 2011
        description: | # this will include new lines to allow paragraphs
            I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      - layout: left
        title: Express Scripts
        link: www.express-scripts.com
        #  link_text: tiaa.org
        sub_title: Senior Java Engineer
        caption: June 2010 - October 2010
        description: | # this will include new lines to allow paragraphs
            I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      - layout: left
        title: State of Maryland
        link: www.courts.state.md.us
        #  link_text: tiaa.org
        sub_title: Senior Java Engineer
        caption: July 2009 - June 2010
        description: | # this will include new lines to allow paragraphs
            I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      - layout: left
        title: Jackson National Life Insurance
        link: www.jackson.com
        #  link_text: tiaa.org
        sub_title: Senior Java Engineer
        caption: June 2008 - June 2009
        description: | # this will include new lines to allow paragraphs
            I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Previous Experience
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Ciberwiz Inc : January 2008 – June 2008 Senior Java Engineer
      - First State Bank of East Detroit : June 2006 – December 2007 Java Engineer
      - Globe Tech, Inc, Detroit: February 2005 – June 2006 Java Engineer
      - Expert Desk (Pvt. Ltd), Lahore: April 2004 – December 2004 Analyst/Java Developer
      - Power Developers Inc, Gujranwala: January 2002 – April 2004 Java Developer
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UCP
        caption: 2001 - 2004
        sub_title: MSc Computer Science
        quote: > 
          A child without education is like a bird without wings.          
        description: | # this will include new lines to allow paragraphs
          During my time at UCP I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  - title: When I'm Not Programming
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering some of my other interests and hobbies are:
      - Cricket
      - Gaming
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-minimal
