# Site
repository: geminiperseus.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hur Muhammad
title: Solutions Architect
email: hur.info@gmail.com
website: www.github.com/geminiperseus

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: https://www.linkedin.com/in/geminiperseus
github_username:  geminiperseus

#instagram_username: https://www.linkedin.com/in/geminiperseus
linkedin_username: https://www.linkedin.com/in/geminiperseus


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  <br /> Highly accomplished Technology Leader with an active DoD security clearance and over 20 years of experience in the IT industry. Proven track record in driving innovation, delivering strategic solutions, and leading teams in high-pressure environments. Expert in implementing cutting-edge technologies to facilitate digital transformation, cloud migration, and intelligent automation, resulting in enhanced customer experience, optimized business operations, reduced costs, and increased revenue. Recognized as a visionary architect with deep expertise in Java and J2EE technologies, I am passionate about leveraging technology to solve complex business challenges and achieve tangible outcomes.

content:      
  - title: Value Proposition # Title for the section
    layout: text # Type of content section (list/text)
    content: | 
      - Transforming business needs to value driven solutions in collaboration with all stakeholders
      - Leading large, complex global products delivery with major focus on Big Data, AI/ML and Cloud technologies
      - Consistently leading complex, challenging, high visible, fast-paced and demanding firm wide initiatives
      - Driving Artificial Intelligence/Machine Learning (AI/ML) strategy and Public Cloud blueprints for products transformation within a technology organization
      - Creating business value through successful AI/ML and Cloud POCs leading to solutions in production
      - Promoting inclusiveness and partnership by engaging all required teams to build solutions
  - title: TECHNICAL PROFICIENCY
    layout: text
    content: |
      -	Expert in programming languages Java, C#, VB.NET, PHP, Cold Fusion and Python
      -	Strong knowledge of Struts, Spring (MVC, Web Flow), Spring boot, JSP, Servlets and various design patterns to ensure maintainable and scalable code
      -	Proficient in AJAX, JavaScript, Angular, React, HTML, XML, jQuery, and DOJO for Rich Internet Applications
      -	Skilled in designing and consuming web services (XML-RPC, SOAP, WSDL, RESTful) for seamless system integration
      -	Developed and managed infrastructure as code (IaC) using AWS CloudFormation and Terraform for efficient resource provisioning.
      -	Extensive experience with Oracle, Postgres, Mongo, SQL Server, and MySQL, including SQL and PL/SQL development for efficient data handling
      -	Excellent communicator and proactive team player, adept at engaging stakeholders, driving projects forward, and leading cross-functional teams
      -	Proficient in designing, deploying, and managing applications on AWS using services such as EC2, S3, RDS, EKS, Route53, Cloud Front etc.
      -	Proficient in designing and building big data applications using Java with Apache Spark and the Hadoop ecosystem (Hive, Sqoop, Hive SQL, Map reduce, Pig script), optimizing data processing capabilities through efficient use of Spark's in-memory computation and Hadoop's distributed storage. Experienced in developing ETL processes to ingest, transform, and analyze large datasets, leading to improved decision-making and operational efficiency.

  - title: EXPERIENCE # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: left
        title: USCIS
        link: www.uscis.com
        #  link_text: uscis.com
        sub_title: Solutions Architect
        caption: Sep 2023 - Present
        description: | # this will include new lines to allow paragraphs
          The E-Verify application is a free, internet-based system that helps employers confirm a new hire's employment eligibility. <br/>
          - Designed and deployed new features for the web application using Spring Boot and AWS services (EC2, S3, EKS), enhancing user experience and functionality.
          -	Established automated deployment pipelines with GitHub Actions, significantly enhancing CI/CD efficiency and reducing manual errors.
          -	Developed RESTful APIs, integrated Istio service mesh for improved microservices management, ensuring seamless communication and reliability.
          -	Created and maintained an automated testing framework using Cucumber, incorporating mocks and Gherkin syntax for behavior-driven development (BDD), increasing test coverage and quality.
          -	Developed and maintained cloud infrastructure with AWS services, utilizing CloudFormation for provisioning and CloudWatch for monitoring, leading to improved operational efficiency.
          -	Established security best practices across AWS services, focusing on IAM for access control, KMS for encryption, and CloudTrail for logging and auditing to meet federal compliance requirements.
          -	Developed and implemented automated backup and disaster recovery solutions using AWS services (EBS for storage and S3 for data redundancy), ensuring data integrity and availability.

      - layout: right
        title: Thrivent
        link: www.thrivent.com
        #  link_text: thrivent.com
        sub_title: Solutions Architect
        caption: November 2020 - Aug 2023
        description: | # this will include new lines to allow paragraphs
          Thrivent’s Mobile App provides a personalized and secure way to manage finances, including insurance and investment accounts. <br/>
          - Designed and developed RESTful APIs and GraphQL endpoints to facilitate seamless communication between front-end and back-end systems, optimizing data exchange and user experience.
          -	Implemented API authentication and authorization using OAuth 2.0 and JWT for REST APIs, enhancing security and user access control.
          -	Developed flexible GraphQL schemas to enable clients to request only the data they need, improving efficiency and reducing payload sizes.
          -	Collaborated with cross-functional teams to define API requirements and specifications, ensuring alignment with business objectives and user needs.
          -	Monitored and logged API usage and performance metrics using tools like AWS CloudWatch and ELK Stack, facilitating proactive issue resolution.
          -	Developed API versioning strategies for REST APIs to maintain backward compatibility while introducing new features and enhancements.
          -	Created comprehensive API documentation for both REST and GraphQL, improving usability and adoption among developers and stakeholders.
          -	Developed a tool for generating marketing and promotional emails, streamlining customer outreach and engagement efforts.
          -	Successfully migrated Kong API Gateway to Istio service mesh on Elastic Kubernetes (EKS), resulting in a 50% reduction in infrastructure costs and a 40% increase in scalability.
          -	Developed CI/CD pipelines for REST APIs using GitHub Actions, leading to a 60% reduction in deployment time and a 30% increase in deployment frequency.
          -	Managed cloud infrastructure using AWS services, including CloudFormation and CloudWatch, achieving a 25% reduction in downtime and a 20% increase in application availability. 


      - layout: left
        title: TIAA Cref
        link: www.tiaa.org
        #  link_text: tiaa.org
        sub_title: Big Data Architect
        caption: September 2016 - November 2020
        description: | # this will include new lines to allow paragraphs
          Led various projects to develop financial management tools for investment managers.<br/>
          - Enhanced existing features and developed new functionalities for the GOFOLIO application, improving user interface design with Free Marker templates and jQuery.
          - Created the SFV Designer from scratch using Angular 2 and Spring Boot, allowing operations to create new services and features efficiently.
          - Implemented rolling data sources to efficiently store and manage data across multiple databases, leveraging Hadoop for accurate fee calculations for clients.
          - Designed and implemented big data solutions using Hadoop ecosystem components, including HDFS, MapReduce, Hive, and Pig for Fee Calculation Engine.
          -	Implemented data ingestion processes using Apache Sqoop, facilitating seamless data transfer from relational databases and streaming sources into HDFS.
          - Ensured data security and compliance by implementing Hadoop security features, including Kerberos authentication and HDFS encryption.
          - Conducted troubleshooting and performance tuning of Hadoop jobs, reducing execution time and resource consumption.
          - Successfully transitioned the Fee Calculation Engine to AWS Cloud (EMR), enhancing scalability and resource utilization while reducing operational costs.
          - Developed business rules using Rule Book to improve application logic and wrote REST services to fetch data from an Oracle database seamlessly.
          - Employed Log4j for effective logging and debugging and implemented unit tests with JUnit to ensure code reliability and maintainability.


      - layout: right
        title: Capital One
        link: www.capitalone.org
        #  link_text: tiaa.org
        sub_title: Tech Lead
        caption: September 2011 - September 2016
        description: | # this will include new lines to allow paragraphs
          Executed multiple projects for Bank and Card division by managing strategy and operations whilst ensuring adherence to regulatory compliance like ADA, CFPB, AML, FDIC and Dodd-Frank. <br/> 
          - <b>Implemented Robotic Automation</b> in Call Centers and Mortgage Line of Business: Led product strategy, architecture and development for the pioneer initiative to implement Robotic automations in Capital One call centers. Automated and deployed 16 processes across 5 call centers that resulted in anticipated saving ~3 million dollars in the very first year.  Responsible for architecture design, coding, testing and product release. 
          - <b>Implemented the next gen CTI/IVR platform</b> for Contact Centers:  Evaluated next gen CTI/IVR platforms for Retail Banking Contact Centers from various vendors such as Avaya and Cisco. Integrated Omni-Channel platforms that resulted from acquisitions. Implemented Voice Biometric Authentication using NICE platform in contact centers for customer authentication.
          - <b>Led AWS Cloud Migration and Enterprise Product Development:</b> As solution architect led the cloud first initiative by migrating their existing legacy applications to AWS platform. Re-engineered architecture by moving from traditional web services to APIs and micro services. Led and manage multiple agile development teams (on Java, Cassandra, ASP.NET, C#, SQL Server, Node.js, jQuery and JS using RESTful API’s and micro services-). DevOps and Automation using CICD tools such as Jenkins/Maven). 
          - <b>Developed EBrochure:</b> Developed EBrochure application using angular JS and Reset APIs. This application is used to refer new clients that visit Capital One Café.
          - <b>Developed automated call routing:</b> Developed automated call routing for customers who contacted capital one customer services based on customer activity on the website or mobile application. This reduced call time by approximately 50%.
          - <b>Developed Automation Framework:</b> Led a team to develop an automation framework (using selenium, cucumber and java) which was used to automate the testing of capital one 360 website and call center application.
      - layout: left
        title: State of Maryland
        link: www.courts.state.md.us
        #  link_text: tiaa.org
        sub_title: Senior Java Engineer
        caption: October 2010 - September 2011
        description: | # this will include new lines to allow paragraphs
          <b>Developed Case Management System</b> as Rich Intranet Application (RIA) using Java, JavaScript, Oracle and Hibernate wherein employee can view and mange different stage of a case. Built the project as a test driven development application using mocking framework.
      - layout: right
        title: Express Scripts
        link: www.express-scripts.com
        #  link_text: tiaa.org
        sub_title: Senior Java Engineer
        caption: June 2010 - October 2010
        description: | # this will include new lines to allow paragraphs
          - <b>Designed and Developed Interactive IVR Framework</b> to connect existing XML front end to existing web services using spring framework to provide interactive IVR experience without talking to a representative.
          - <b>Developed Exception Handling Framework</b> to display errors happening in the backend and middle ware on the UI.
          - <b>Designed and developed a testing frame work</b> using Selenium, Java, Junits, Mockito. 
      - layout: left
        title: State of Maryland
        link: www.courts.state.md.us
        #  link_text: tiaa.org
        sub_title: Senior Java Engineer
        caption: July 2009 - June 2010
        description: | # this will include new lines to allow paragraphs
          <b>Designed and developed accounting application</b> to gather revenue from all circuit courts and the district courts in the state of Maryland. Application gather data from the registers placed in different courts in the state and save it to the central database. The clerks of the courts can make adjustments on the money collected in the courts using this application.
      - layout: right
        title: Jackson National Life Insurance
        link: www.jackson.com
        #  link_text: tiaa.org
        sub_title: Senior Java Engineer
        caption: June 2008 - June 2009
        description: | # this will include new lines to allow paragraphs
          <b>Enhanced and Transformed Curian Capital, LLC</b> a registered investment advisor that provides a fee-based separately managed account (SMA) platform to financial professionals. With the investor’s personal goals and objectives in mind, Curian Capital and the Financial Professional work together to deliver a comprehensive investment plan that reflects the appropriate risk level for the investor. Investors receive an Investment Policy Statement or financial “roadmap” customized around their unique objectives and risk profile. Curian leverages its internal expertise and that of Rogers Casey, one of the largest investment consultants in the world, to select investment managers and construct portfolios. Each portfolio is designed to pursue optimal performance at the investor’s chosen risk level.

  - title: PRIOR EXPERIENCE
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Ciberwiz Inc : January 2008 – June 2008 Senior Java Engineer
      - First State Bank of East Detroit : June 2006 – December 2007 Java Engineer
      - Globe Tech, Inc, Detroit: February 2005 – June 2006 Java Engineer
      - Expert Desk (Pvt. Ltd), Lahore: April 2004 – December 2004 Analyst/Java Developer
      - Power Developers Inc, Gujranwala: January 2002 – April 2004 Java Developer
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UCP
        caption: 2001 - 2004
        sub_title: MSc Computer Science

# Footer
footer_show_references: false
# references_title: References on request (Override references text

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-minimal
